version: 2
jobs:
  build:
    docker:
      - image: makarius/isabelle:Isabelle2018

    steps:
      - checkout

      - run:
          name: Isabelle Build
          command: ~/Isabelle/bin/isabelle build -D src
