version: 2
jobs:
  build:
    docker:
      - image: makarius/isabelle:Isabelle2018

    steps:
      - checkout

      - run:
          name: Isabelle Test
          command: Isabelle/bin/isabelle version
